"""empty message

Revision ID: 94e5d9ce854c
Revises: 1fb7c27973cf
Create Date: 2025-04-12 23:45:11.769329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e5d9ce854c'
down_revision = '1fb7c27973cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
