"""Add user_task_id to Task

Revision ID: ddd0945caa89
Revises: c8dba8167db1
Create Date: 2025-04-09 22:09:56.661380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd0945caa89'
down_revision = 'c8dba8167db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_task_uc', ['user_id', 'user_task_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('user_task_uc', type_='unique')

    # ### end Alembic commands ###
